create table UsuCont(
Id_UsuCont BIGINT PRIMARY KEY IDENTITY,
ID_USUARIO BIGINT NOT NULL,
FOREIGN KEY (ID_USUARIO) REFERENCES Usuario(ID_USUARIO),
ID_CONTRATO BIGINT NOT NULL,
FOREIGN KEY (ID_CONTRATO) REFERENCES Contrato(ID_CONTRATO)
)


INSERT INTO UsuCont (ID_USUARIO, ID_CONTRATO) VALUES (2, 1)
INSERT INTO UsuCont (ID_USUARIO, ID_CONTRATO) VALUES (1, 1)
INSERT INTO UsuCont (ID_USUARIO, ID_CONTRATO) VALUES (2, 2)
INSERT INTO UsuCont (ID_USUARIO, ID_CONTRATO) VALUES (1, 2)